<?php
/**
 * localized routing (e.g. CONTROLLER-ACTION)
 */

return [
    'file-show' => [
        'route'      => '/de/datei/{uuid}/',
        'method'     => 'App\Controller\FileController:showAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['guest', 'member', 'admin', 'superadmin'],
        'rolesDeny'  => [],
    ],
    'file-upload' => [
        'route'      => '/de/datei/hochladen/',
        'method'     => 'App\Controller\FileController:uploadAction',
        'methods'    => ['POST'],
        'rolesAllow' => ['member', 'admin', 'superadmin'],
        'rolesDeny'  => [],
    ],
    'file-hidden' => [
        'route'      => '/de/datei/versteckt/{uuid}/',
        'method'     => 'App\Controller\FileController:toggleHiddenAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['member', 'admin', 'superadmin'],
        'rolesDeny'  => [],
    ],
    'file-remove' => [
        'route'      => '/de/datei/loeschen/{uuid}/',
        'method'     => 'App\Controller\FileController:removeAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['member', 'admin', 'superadmin'],
        'rolesDeny'  => [],
    ],
    'file-extension-create' => [
        'route'      => '/de/dateiendung/erstellen/',
        'method'     => 'App\Controller\FileExtensionController:createAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['superadmin'],
        'rolesDeny'  => [],
    ],
    'file-extension-save' => [
        'route'      => '/de/dateiendung/speichern/',
        'method'     => 'App\Controller\FileExtensionController:saveCreateAction',
        'methods'    => ['POST'],
        'rolesAllow' => ['superadmin'],
        'rolesDeny'  => [],
    ],
    'file-extension-show' => [
        'route'      => '/de/dateiendung/',
        'method'     => 'App\Controller\FileExtensionController:showAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['superadmin'],
        'rolesDeny'  => [],
    ],
    'file-extension-hidden' => [
        'route'      => '/de/dateiendung/versteckt/{id}/',
        'method'     => 'App\Controller\FileExtensionController:toggleHiddenAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['superadmin'],
        'rolesDeny'  => [],
    ],
    'file-extension-remove' => [
        'route'      => '/de/dateiendung/loeschen/{id}/',
        'method'     => 'App\Controller\FileExtensionController:removeAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['superadmin'],
        'rolesDeny'  => [],
    ],
    'user-enable-two-factor' => [
        'route'      => '/de/zwei-faktor-aktivieren/',
        'method'     => 'App\Controller\UserController:enableTwoFactorAction',
        'methods'    => ['GET', 'POST'],
        'rolesAllow' => ['member', 'admin', 'superadmin'],
        'rolesDeny'  => [],
    ],
    'user-two-factor' => [
        'route'      => '/de/zwei-faktor/',
        'method'     => 'App\Controller\UserController:twoFactorAction',
        'methods'    => ['GET', 'POST'],
        'rolesAllow' => ['guest', 'member', 'admin', 'superadmin'],
        'rolesDeny'  => [],
    ],
    'user-show' => [
        'route'      => '/de/profil/[{name}/]',
        'method'     => 'App\Controller\UserController:showAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['guest', 'member', 'admin', 'superadmin'],
        'rolesDeny'  => [],
    ],
    'user-show-all' => [
        'route'      => '/de/profile/',
        'method'     => 'App\Controller\UserController:showAllAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['superadmin'],
        'rolesDeny'  => [],
    ],
    'user-update-role' => [
        'route'      => '/de/rolle/{role}/{name}/',
        'method'     => 'App\Controller\UserController:updateRoleAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['superadmin'],
        'rolesDeny'  => [],
    ],
    'user-create' => [
        'route'      => '/de/user/create/',
        'method'     => 'App\Controller\UserController:createAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['superadmin'],
        'rolesDeny'  => [],
    ],
    'user-save' => [
        'route'      => '/de/user/save/',
        'method'     => 'App\Controller\UserController:saveCreateAction',
        'methods'    => ['POST'],
        'rolesAllow' => ['superadmin'],
        'rolesDeny'  => [],
    ],
    'user-register' => [
        'route'      => '/de/registrieren/',
        'method'     => 'App\Controller\UserController:registerAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['guest'],
        'rolesDeny'  => [],
    ],
    'user-register-save' => [
        'route'      => '/de/registrierung-abschliessen/',
        'method'     => 'App\Controller\UserController:saveRegisterAction',
        'methods'    => ['POST'],
        'rolesAllow' => ['guest'],
        'rolesDeny'  => [],
    ],
    'user-hidden' => [
        'route'      => '/de/user/versteckt/{name}/',
        'method'     => 'App\Controller\UserController:toggleHiddenAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['superadmin'],
        'rolesDeny'  => [],
    ],
    'user-remove' => [
        'route'      => '/de/user/remove/{name}/',
        'method'     => 'App\Controller\UserController:removeAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['superadmin'],
        'rolesDeny'  => [],
    ],
    
    // this routes fits to all translations
    'file-download' => [
        'route'      => '/de/download/{uuid}/',
        'method'     => 'App\Controller\FileController:downloadAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['guest', 'member', 'admin', 'superadmin'],
        'rolesDeny'  => [],
    ],
    'user-login-validate' => [
        'route'      => '/de/validate/',
        'method'     => 'App\Controller\UserController:loginValidateAction',
        'methods'    => ['POST'],
        'rolesAllow' => ['guest', 'member', 'admin', 'superadmin'],
        'rolesDeny'  => [],
    ],
    'user-login' => [
        'route'      => '/de/login/',
        'method'     => 'App\Controller\UserController:loginAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['guest', 'member', 'admin', 'superadmin'],
        'rolesDeny'  => [],
    ],
    'user-logout' => [
        'route'      => '/de/logout/',
        'method'     => 'App\Controller\UserController:logoutAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['guest', 'member', 'admin', 'superadmin'],
        'rolesDeny'  => [],
    ],
    'error-bad-request' => [
        'route'      => '/de/400/',
        'method'     => 'App\Controller\ErrorController:badRequestAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['guest', 'member', 'admin', 'superadmin'],
        'rolesDeny'  => [],
    ],
    'error-not-allowed' => [
        'route'      => '/de/405/',
        'method'     => 'App\Controller\ErrorController:notAllowedAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['guest', 'member', 'admin', 'superadmin'],
        'rolesDeny'  => [],
    ],
    'error-not-found' => [
        'route'      => '/de/404/',
        'method'     => 'App\Controller\ErrorController:notFoundAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['guest', 'member', 'admin', 'superadmin'],
        'rolesDeny'  => [],
    ],
    'error-unauthorized' => [
        'route'      => '/de/401/',
        'method'     => 'App\Controller\ErrorController:unauthorizedAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['guest', 'member', 'admin', 'superadmin'],
        'rolesDeny'  => [],
    ],
    'page-index' => [
        'route'      => '/de/',
        'method'     => 'App\Controller\PageController:indexAction',
        'methods'    => ['GET'],
        'rolesAllow' => ['guest', 'member', 'admin', 'superadmin'],
        'rolesDeny'  => [],
    ],
];